<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

<script>
  // setTimeout(() => {
  //   console.log("hello world");
  // }, 1000)

  // resolve,reject本身他们又是函数
  // new Promise((resolve, reject) => {

  //   // 模拟第一次拿到结果的处理代码
  //   setTimeout(() => {
  //     resolve()
  //   }, 1000)
  // }).then(() => {
  //   console.log('Hello World');
  //   console.log('Hello World');
  //   console.log('Hello World');
  //
  //   return new Promise((resolve, reject) => {
  //
  //     // 模拟第二次网络请求的代码
  //     setTimeout(() => {
  //       resolve()
  //     }, 1000)
  //   }).then(() => {
  //
  //     // 第二次处理的代码
  //     console.log('Hello Vuejs');
  //     console.log('Hello Vuejs');
  //     console.log('Hello Vuejs');
  //
  //     return new Promise((resolve, reject) => {
  //
  //       // 第三次拿到结果的处理代码
  //       setTimeout(() => {
  //         resolve()
  //       })
  //     }).then(() => {
  //       // 第三次处理的代码
  //       console.log('Hello Java');
  //       console.log('Hello Java');
  //       console.log('Hello Java');
  //     })
  //   })
  // })

  // 什么情况下回用到Promise？
  // 一般情况下是有异步操作时，使用Promise对这个异步操作进行封装
  // new -> 构造函数(1.保存了一些状态信息，2.执行转入的函数)
  // 在执行传入的回调函数时，会传入两个参数，resolve,reject,本身又是函数
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('hello world');
      // 失败的时候调用reject
      reject('error message');
    }, 1000)
  }).then(data => {
    console.log(data);
  }).catch(err => {
    console.log(err)
  })
</script>

</body>
</html>